# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'distanceFinder' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for distanceFinder
pod 'DistanceGetter','~> 0.1'
  target 'distanceFinderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'distanceFinderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
